### ISSUE TITLE
Segfault on playing midi files with external rtmidi

### ISSUE THREAD

**Issue by glixx** [pianobooster/PianoBooster#102]
http://piano-booster.2625608.n2.nabble.com/attachment/4582249/0/teachmid.tar.gz

terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

**Comment by glixx** [comment]
```
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

Thread 1 "pianobooster" received signal SIGABRT, Aborted.
0x00007ffff68f9a7a in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install dconf-0.30.1-1.mga7.x86_64 gvfs-1.38.1-3.mga7.x86_64 lib64GConf2_4-3.2.6-17.mga7.x86_64 lib64alsa2-1.1.9-1.mga7.x86_64 lib64asyncns0-0.8-11.mga7.x86_64 lib64atk-bridge2.0_0-2.32.0-2.mga7.x86_64 lib64atk1.0_0-2.32.0-2.mga7.x86_64 lib64atspi0-2.32.1-2.mga7.x86_64 lib64bsd0-0.9.1-3.mga7.x86_64 lib64bz2_1-1.0.6-12.mga7.x86_64 lib64cairo2-1.16.0-2.mga7.x86_64 lib64canberra-gtk3_0-0.30-12.mga7.x86_64 lib64canberra0-0.30-12.mga7.x86_64 lib64datrie1-0.2.12-1.mga7.x86_64 lib64dbus-glib1_2-0.110-2.mga7.x86_64 lib64dbus1_3-1.13.8-2.mga7.x86_64 lib64dri-drivers-19.1.0-0.rc4.1.mga7.x86_64 lib64drm2-2.4.98-1.mga7.x86_64 lib64drm_intel1-2.4.98-1.mga7.x86_64 lib64drm_radeon1-2.4.98-1.mga7.x86_64 lib64expat1-2.2.6-2.mga7.x86_64 lib64ffi6-3.2.1-7.mga7.x86_64 lib64flac8-1.3.2-3.mga7.x86_64 lib64fluidsynth2-2.0.5-1.mga7.x86_64 lib64fontconfig1-2.13.1-1.mga7.x86_64 lib64freetype6-2.9.1-4.mga7.x86_64 lib64fribidi0-1.0.5-2.mga7.x86_64 lib64ftgl2-2.1.3-0.rc5.15.mga7.x86_64 lib64gdk_pixbuf2.0_0-2.38.1-3.mga7.x86_64 lib64gio2.0_0-2.60.2-1.mga7.x86_64 lib64glapi0-19.1.0-0.rc4.1.mga7.x86_64 lib64glib2.0_0-2.60.2-1.mga7.x86_64 lib64gpg-error0-1.36-1.mga7.x86_64 lib64graphite2_3-1.3.13-1.mga7.x86_64 lib64gtk+3_0-3.24.8-1.mga7.x86_64 lib64harfbuzz0-2.4.0-1.mga7.x86_64 lib64ice6-1.0.9-6.mga7.x86_64 lib64icu63-63.1-1.mga7.x86_64 lib64jack0-1.9.12-2.mga7.x86_64 lib64lz4_1-1.8.3-1.mga7.x86_64 lib64lzma5-5.2.4-2.mga7.x86_64 lib64mesagl1-19.1.0-0.rc4.1.mga7.x86_64 lib64mesaglu1-9.0.0-8.mga7.x86_64 lib64ncurses6-6.1-20181117.3.mga7.x86_64 lib64ogg0-1.3.3-5.mga7.x86_64 lib64pango1.0_0-1.43.0-3.mga7.x86_64 lib64pciaccess0-0.14-2.mga7.x86_64 lib64pcre1-8.43-1.mga7.x86_64 lib64png16_16-1.6.37-1.mga7.x86_64 lib64portaudio2-19.6.0-snapshot20161030.6.mga7.x86_64 lib64pulseaudio0-12.2-5.mga7.x86_64 lib64pulsecommon12.2-12.2-4.mga7.x86_64 lib64qt5core5-5.12.2-2.mga7.x86_64 lib64qt5dbus5-5.12.2-2.mga7.x86_64 lib64qt5gui5-5.12.2-2.mga7.x86_64 lib64qt5opengl5-5.12.2-2.mga7.x86_64 lib64qt5widgets5-5.12.2-2.mga7.x86_64 lib64qt5xcbqpa5-5.12.1-1.mga7.x86_64 lib64qt5xml5-5.12.2-2.mga7.x86_64 lib64readline7-7.0-3.mga7.x86_64 lib64rtmidi5-4.0.0-1.mga7.x86_64 lib64sm6-1.2.3-1.mga7.x86_64 lib64sndfile1-1.0.28-8.mga7.x86_64 lib64systemd0-241-8.mga7.x86_64 lib64thai0-0.1.28-1.mga7.x86_64 lib64uuid1-2.33.2-1.mga7.x86_64 lib64vorbis0-1.3.6-3.mga7.x86_64 lib64wayland-client0-1.17.0-1.mga7.x86_64 lib64wayland-cursor0-1.17.0-1.mga7.x86_64 lib64wayland-server0-1.17.0-1.mga7.x86_64 lib64wrap0-7.6-48.mga7.x86_64 lib64x11_6-1.6.7-1.mga7.x86_64 lib64xau6-1.0.9-1.mga7.x86_64 lib64xcb-dri2_0-1.13.1-1.mga7.x86_64 lib64xcb-dri3_0-1.13.1-1.mga7.x86_64 lib64xcb-glx0-1.13.1-1.mga7.x86_64 lib64xcb-icccm4-0.4.1-5.mga7.x86_64 lib64xcb-present0-1.13.1-1.mga7.x86_64 lib64xcb-randr0-1.13.1-1.mga7.x86_64 lib64xcb-shape0-1.13-2.mga7.x86_64 lib64xcb-shape0-1.13.1-1.mga7.x86_64 lib64xcb-shm0-1.13.1-1.mga7.x86_64 lib64xcb-sync1-1.13.1-1.mga7.x86_64 lib64xcb-util-image0-0.4.0-3.mga7.x86_64 lib64xcb-util-keysyms1-0.4.0-4.mga7.x86_64 lib64xcb-util-renderutil0-0.3.9-5.mga7.x86_64 lib64xcb-util1-0.4.0-3.mga7.x86_64 lib64xcb-xinput0-1.13.1-1.mga7.x86_64 lib64xcb-xkb1-1.13.1-1.mga7.x86_64 lib64xcb1-1.13.1-1.mga7.x86_64 lib64xdamage1-1.1.5-1.mga7.x86_64 lib64xext6-1.3.4-1.mga7.x86_64 lib64xi6-1.7.9-3.mga7.x86_64 lib64xkbcommon0-0.8.4-1.mga7.x86_64 lib64xrandr2-1.5.2-1.mga7.x86_64 lib64xshmfence1-1.3-2.mga7.x86_64 lib64xxf86vm1-1.1.4-3.mga7.x86_64 lib64zlib1-1.2.11-7.mga7.x86_64 libstdc++6-8.3.1-0.20190524.1.mga7.x86_64
(gdb) bt
#0  0x00007ffff68f9a7a in raise () at /lib64/libc.so.6
#1  0x00007ffff68e2524 in abort () at /lib64/libc.so.6
#2  0x00007ffff6b2e9a3 in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] ()
    at /lib64/libstdc++.so.6
#3  0x00007ffff6b348e6 in __cxxabiv1::__terminate(void (*)()) () at /lib64/libstdc++.so.6
#4  0x00007ffff6b34921 in  () at /lib64/libstdc++.so.6
#5  0x00007ffff6b34b53 in  () at /lib64/libstdc++.so.6
#6  0x00007ffff6b308b1 in std::__throw_out_of_range_fmt(char const*, ...) [clone .cold.5] ()
    at /lib64/libstdc++.so.6
#7  0x000000000045f790 in CMidiDeviceRt::playMidiEvent(CMidiEvent const&) ()
#8  0x00000000004598f4 in CConductor::playTrackEvent(CMidiEvent) ()
#9  0x000000000045b831 in CConductor::realTimeEngine(int) ()
#10 0x0000000000458659 in CSong::task(int) ()
#11 0x0000000000452b8b in CGLView::updateMidiTask() ()
#12 0x0000000000452c30 in CGLView::paintGL() ()
#13 0x00007ffff7dfef29 in QGLWidget::glDraw() () at /lib64/libQt5OpenGL.so.5
#14 0x0000000000452d34 in CGLView::timerEvent(QTimerEvent*) ()
#15 0x00007ffff6ebcc8b in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#16 0x00007ffff78e0cdb in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#17 0x00007ffff78a3a31 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#18 0x00007ffff78aa960 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#19 0x00007ffff6e93e69 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#20 0x00007ffff6ee3d33 in QTimerInfoList::activateTimers() () at /lib64/libQt5Core.so.5
#21 0x00007ffff6ee451c in  () at /lib64/libQt5Core.so.5
#22 0x00007ffff6418665 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#23 0x00007ffff64189e8 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#24 0x00007ffff6418a6c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#25 0x00007ffff6ee4847 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib64/libQt5Core.so.5
#26 0x00007ffff6e92c1b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
--Type <RET> for more, q to quit, c to continue without paging--
    at /lib64/libQt5Core.so.5
#27 0x00007ffff6e9a8c8 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#28 0x000000000042368e in main ()
(gdb) bt
#0  0x00007ffff68f9a7a in raise () at /lib64/libc.so.6
#1  0x00007ffff68e2524 in abort () at /lib64/libc.so.6
#2  0x00007ffff6b2e9a3 in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] ()
    at /lib64/libstdc++.so.6
#3  0x00007ffff6b348e6 in __cxxabiv1::__terminate(void (*)()) () at /lib64/libstdc++.so.6
#4  0x00007ffff6b34921 in  () at /lib64/libstdc++.so.6
#5  0x00007ffff6b34b53 in  () at /lib64/libstdc++.so.6
#6  0x00007ffff6b308b1 in std::__throw_out_of_range_fmt(char const*, ...) [clone .cold.5] ()
    at /lib64/libstdc++.so.6
#7  0x000000000045f790 in CMidiDeviceRt::playMidiEvent(CMidiEvent const&) ()
#8  0x00000000004598f4 in CConductor::playTrackEvent(CMidiEvent) ()
#9  0x000000000045b831 in CConductor::realTimeEngine(int) ()
#10 0x0000000000458659 in CSong::task(int) ()
#11 0x0000000000452b8b in CGLView::updateMidiTask() ()
#12 0x0000000000452c30 in CGLView::paintGL() ()
#13 0x00007ffff7dfef29 in QGLWidget::glDraw() () at /lib64/libQt5OpenGL.so.5
#14 0x0000000000452d34 in CGLView::timerEvent(QTimerEvent*) ()
#15 0x00007ffff6ebcc8b in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#16 0x00007ffff78e0cdb in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#17 0x00007ffff78a3a31 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#18 0x00007ffff78aa960 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#19 0x00007ffff6e93e69 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#20 0x00007ffff6ee3d33 in QTimerInfoList::activateTimers() () at /lib64/libQt5Core.so.5
#21 0x00007ffff6ee451c in  () at /lib64/libQt5Core.so.5
#22 0x00007ffff6418665 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#23 0x00007ffff64189e8 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#24 0x00007ffff6418a6c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#25 0x00007ffff6ee4847 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib64/libQt5Core.so.5
#26 0x00007ffff6e92c1b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
--Type <RET> for more, q to quit, c to continue without paging--RET
    at /lib64/libQt5Core.so.5
#27 0x00007ffff6e9a8c8 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#28 0x000000000042368e in main ()
(gdb) bt
#0  0x00007ffff68f9a7a in raise () at /lib64/libc.so.6
#1  0x00007ffff68e2524 in abort () at /lib64/libc.so.6
#2  0x00007ffff6b2e9a3 in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] ()
    at /lib64/libstdc++.so.6
#3  0x00007ffff6b348e6 in __cxxabiv1::__terminate(void (*)()) () at /lib64/libstdc++.so.6
#4  0x00007ffff6b34921 in  () at /lib64/libstdc++.so.6
#5  0x00007ffff6b34b53 in  () at /lib64/libstdc++.so.6
#6  0x00007ffff6b308b1 in std::__throw_out_of_range_fmt(char const*, ...) [clone .cold.5] ()
    at /lib64/libstdc++.so.6
#7  0x000000000045f790 in CMidiDeviceRt::playMidiEvent(CMidiEvent const&) ()
#8  0x00000000004598f4 in CConductor::playTrackEvent(CMidiEvent) ()
#9  0x000000000045b831 in CConductor::realTimeEngine(int) ()
#10 0x0000000000458659 in CSong::task(int) ()
#11 0x0000000000452b8b in CGLView::updateMidiTask() ()
#12 0x0000000000452c30 in CGLView::paintGL() ()
#13 0x00007ffff7dfef29 in QGLWidget::glDraw() () at /lib64/libQt5OpenGL.so.5
#14 0x0000000000452d34 in CGLView::timerEvent(QTimerEvent*) ()
#15 0x00007ffff6ebcc8b in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#16 0x00007ffff78e0cdb in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#17 0x00007ffff78a3a31 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#18 0x00007ffff78aa960 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#19 0x00007ffff6e93e69 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#20 0x00007ffff6ee3d33 in QTimerInfoList::activateTimers() () at /lib64/libQt5Core.so.5
#21 0x00007ffff6ee451c in  () at /lib64/libQt5Core.so.5
#22 0x00007ffff6418665 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#23 0x00007ffff64189e8 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#24 0x00007ffff6418a6c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#25 0x00007ffff6ee4847 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib64/libQt5Core.so.5
#26 0x00007ffff6e92c1b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
--Type <RET> for more, q to quit, c to continue without paging--<RET>
    at /lib64/libQt5Core.so.5
#27 0x00007ffff6e9a8c8 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#28 0x000000000042368e in main ()
```

**Comment by glixx** [comment]
```
(gdb) bt
#0  0x00007ffff68f9a7a in raise () at /lib64/libc.so.6
#1  0x00007ffff68e2524 in abort () at /lib64/libc.so.6
#2  0x00007ffff6b2e9a3 in __gnu_cxx::__verbose_terminate_handler() [clone .cold.1] ()
    at /lib64/libstdc++.so.6
#3  0x00007ffff6b348e6 in __cxxabiv1::__terminate(void (*)()) () at /lib64/libstdc++.so.6
#4  0x00007ffff6b34921 in  () at /lib64/libstdc++.so.6
#5  0x00007ffff6b34b53 in  () at /lib64/libstdc++.so.6
#6  0x00007ffff6b308b1 in std::__throw_out_of_range_fmt(char const*, ...) [clone .cold.5] ()
    at /lib64/libstdc++.so.6
#7  0x0000000000460b20 in std::vector<unsigned char, std::allocator<unsigned char> >::_M_range_check(unsigned long) const (__n=<optimized out>, this=<optimized out>) at /usr/include/c++/8.3.1/ext/new_allocator.h:86
#8  0x0000000000460b20 in std::vector<unsigned char, std::allocator<unsigned char> >::at(unsigned long) const
    (__n=<optimized out>, this=<optimized out>) at /usr/include/c++/8.3.1/bits/stl_vector.h:999
#9  0x0000000000460b20 in RtMidiOut::sendMessage(std::vector<unsigned char, std::allocator<unsigned char> > const*) (this=<optimized out>, message=<optimized out>) at /usr/include/rtmidi/RtMidi.h:625
#10 0x0000000000460b20 in CMidiDeviceRt::playMidiEvent(CMidiEvent const&) (this=0x78e8e0, event=...)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/src/MidiDeviceRt.cpp:205
#11 0x000000000045b7d4 in CConductor::playTrackEvent(CMidiEvent) (this=this@entry=0xbe7370, event=...)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/src/Conductor.cpp:433
#12 0x000000000045ba15 in CConductor::playTransposeEvent(CMidiEvent) (this=this@entry=0xbe7370, event=...)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/src/Conductor.cpp:456
#13 0x000000000045bb40 in CConductor::outputSavedNotes() (this=this@entry=0xbe7370)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/src/Queue.h:113
#14 0x000000000045bbba in CConductor::resetWantedChord() (this=this@entry=0xbe7370)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/src/Conductor.cpp:481
#15 0x000000000045a7d9 in CSong::regenerateChordQueue() (this=this@entry=0xbe7370)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/src/Song.cpp:155
#16 0x000000000045a890 in CSong::setPlayMode(int) (this=0xbe7370, mode=0)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/src/Song.cpp:131
#17 0x0000000000424127 in GuiSidePanel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_o=_o@entry=0x5cfe90, _id=_id@entry=8, _a=_a@entry=0x7fffffffce70, _c=QMetaObject::InvokeMetaMethod)
--Type <RET> for more, q to quit, c to continue without paging--<RET>
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/build/build/pianobooster_autogen/EWIEGA46WW/../../../../src/GuiSidePanel.h:134
#18 0x000000000042a8c1 in GuiSidePanel::qt_static_metacall(QObject*, QMetaObject::Call, int, void**)
    (_a=0x7fffffffce70, _id=8, _c=QMetaObject::InvokeMetaMethod, _o=0x5cfe90)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/build/build/pianobooster_autogen/EWIEGA46WW/moc_GuiSidePanel.cpp:189
#19 0x000000000042a8c1 in GuiSidePanel::qt_metacall(QMetaObject::Call, int, void**)
    (this=0x5cfe90, _c=QMetaObject::InvokeMetaMethod, _id=8, _a=0x7fffffffce70)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/build/build/pianobooster_autogen/EWIEGA46WW/moc_GuiSidePanel.cpp:189
#20 0x00007ffff6ebc551 in QMetaObject::activate(QObject*, int, int, void**) () at /lib64/libQt5Core.so.5
#21 0x00007ffff7986612 in QAbstractButton::toggled(bool) () at /lib64/libQt5Widgets.so.5
#22 0x00007ffff7986a21 in  () at /lib64/libQt5Widgets.so.5
#23 0x00007ffff7987f19 in QAbstractButton::setChecked(bool) () at /lib64/libQt5Widgets.so.5
#24 0x00007ffff7987a6d in  () at /lib64/libQt5Widgets.so.5
#25 0x00007ffff7987c80 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () at /lib64/libQt5Widgets.so.5
#26 0x00007ffff78e08e8 in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#27 0x00007ffff78a3a31 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#28 0x00007ffff78ab988 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#29 0x00007ffff6e93e69 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#30 0x00007ffff78a9f7f in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) () at /lib64/libQt5Widgets.so.5
#31 0x00007ffff78fa89c in  () at /lib64/libQt5Widgets.so.5
#32 0x00007ffff78fd6a8 in  () at /lib64/libQt5Widgets.so.5
#33 0x00007ffff78a3a31 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib64/libQt5Widgets.so.5
#34 0x00007ffff78aa960 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#35 0x00007ffff6e93e69 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#36 0x00007ffff72ced7b in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () at /lib64/libQt5Gui.so.5
--Type <RET> for more, q to quit, c to continue without paging--<RET>
#37 0x00007ffff72d0115 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () at /lib64/libQt5Gui.so.5
#38 0x00007ffff72ab4bb in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Gui.so.5
#39 0x00007ffff2ade13a in  () at /lib64/libQt5XcbQpa.so.5
#40 0x00007ffff6418665 in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#41 0x00007ffff64189e8 in g_main_context_iterate.isra () at /lib64/libglib-2.0.so.0
#42 0x00007ffff6418a6c in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#43 0x00007ffff6ee4847 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib64/libQt5Core.so.5
#44 0x00007ffff6e92c1b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /lib64/libQt5Core.so.5
#45 0x00007ffff6e9a8c8 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#46 0x000000000042394e in main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at /usr/src/debug/pianobooster-0.7.0-1.mga7.x86_64/src/QtMain.cpp:46
```

**Comment by glixx** [comment]
Bundled rtmidi is OK.
